### ISSUE TITLE
状态—— 概览　　“ CPU 使用率（%）”显示有 BUG

### ISSUE THREAD

**Issue by geekbb** [1715173329/nanopi-r2s-openwrt#1]
在状态—— 概览　里　“ CPU 使用率（%）”显示有 BUG　　（闲时都在30％左右徘徊）
通过 netdata 插件显示正常在2.5％

**Comment by 1715173329** [comment]
netdata 就是个垃圾，除了占用系统 CPU 以外没有任何意义

**Comment by 1715173329** [comment]
你关了它，CPU 占用立马下降

**Comment by 1715173329** [comment]
还有我的固件不提供 netdata，你哪儿搞来的？

**Comment by geekbb** [comment]
> 还有我的固件不提供netdata，你哪儿搞来的？

我是在系统－软件包里安装的，另：我已换成18.06，没有安装netdata，现在我看“统计”－“图表”，很准！
感谢提供好用固件！

**Comment by geekbb** [comment]
> 还有我的固件不提供netdata，你哪儿搞来的？

我是在系统-软件包里安装的。另：我已换成18.06，没有安装netdata，现在我看“统计” －“图表”，很准！
感谢提供好用固件！

**Comment by geekbb** [comment]
> 还有我的固件不提供netdata，你哪儿搞来的？

我是在系统-软件包里安装的，另：我已换成18.06，没有安装netdata，现在我看“统计” －“图表”，很准！
感谢提供好用固件！
