### ISSUE TITLE
您好，18.06是否可以集成luci-theme-argon主题？

### ISSUE THREAD

**Issue by geekbb** [1715173329/nanopi-r2s-openwrt#3]
我看您的 SHAPSHOT 版本都有luci-theme-argon主题，是否可以在18.06也集成luci-theme-argon主题
[https://github.com/jerrykuku/luci-theme-argon](url)

**Comment by geekbb** [comment]
https://github.com/jerrykuku/luci-theme-argon

**Comment by 1715173329** [comment]
可以，下次加上

**Comment by geekbb** [comment]
美好！
