### ISSUE TITLE
固件是不是没加无线驱动，插入usb无限wifi 启动不起来

### ISSUE THREAD

**Issue by banxianl08** [1715173329/nanopi-r2s-openwrt#6]
固件是不是没加无线驱动，插入usb无限wifi 启动不起来，

**Comment by 1715173329** [comment]
你不说型号我靠算？

**Comment by banxianl08** [comment]
> 你不说型号我靠算？

型号 CF-811AC  芯片组RTL8811CU   不好意思大佬

**Comment by 1715173329** [comment]
> RTL8811CU

这网卡不支持，不用问了

**Comment by banxianl08** [comment]
> > RTL8811CU
> 
> 这网卡不支持，不用问了

那请问大佬哪个网卡支持你做的固件呢，

**Comment by banxianl08** [comment]
> > > RTL8811CU
> > 
> > 
> > 这网卡不支持，不用问了
> 


请问大佬哪个型号的网卡支持大佬做的固件，我这个RTL8811CU是新买的可以用在官方提供的固件，不过官方固件功能太少，想用大神的固件不知哪个型号的网卡可以用，
